version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: fix
      include: scope
